# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools

ENV["FASTLANE_XCODEBUILD_SETTINGS_TIMEOUT"] = "600"

default_platform(:ios)

platform :ios do
  desc "Description of what the lane does"
  lane :metrics do

    scan(scheme: "HealingUP-iOS", 
      code_coverage: true, 
      derived_data_path: "./DerivedData", 
      output_directory: "./sonar-reports",
      devices: "iPhone 8")
     
    slather(cobertura_xml: true, 
      jenkins: true, 
      scheme: "HealingUP-iOS", 
      build_directory: "./DerivedData", 
      output_directory: "./sonar-reports", 
      proj: "./HealingUP-iOS.xcodeproj")

     swiftlint(output_file: "./sonar-reports/swiftlint.txt", 
      ignore_exit_status: true)

     sonar
end
end